title: Fabio Neves
description: is a guy who codes
author: Fabio Neves
collections:
  posts:
    output: true
exclude:
  - bin
  - README.md
  - Gemfile
  - Gemfile.lock

# remote_theme: pages-themes/minimal@v0.2.0
# plugins:
# - jekyll-remote-theme
