title: Fabio Neves
description: is a guy who codes
author: Fabio Neves
source: ./src
destination: ./_site
collections:
  posts:
    output: true

remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme

